AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
    - no014/problem.rb

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false
